# Setup
title:        Metatone
tagline:      Mobile Apps for Making Music
baseurl:      ""
paginate:     1

# About/contact
author: 
  name: Charles Martin
  url: http://metatone.net

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown